Various fixes
- fixed "java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1" when issuing /rpghuds command
- fixed "NoSuchMethodError: 'java.lang.Object dev.lone.itemsadder.api.FontImages.FontImageWrapper.getInternal()'"
- fixed wrongly named png files and removed old unused png files
- added an error message when the money placeholder is not correctly recognized